server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # 👇 AÑADE ESTO: Todo lo que vaya a /api se redirige al contenedor backend
    location /api/ {
        proxy_pass http://java_backend:8080/; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
